### ISSUE TITLE
Usage of request-promise

### ISSUE THREAD

**Issue by KobeGlobal** [xavi-/node-simple-rate-limiter#8]
Does the simple-rate-limiter work with request-promise?

I'm currently getting this error when using it with request-promise

TypeError: requestPromise(...).catch is not a function
    at promiseRetry.retries (C:\project\node_modules\request-promise-retry\index.js:18:27)
    at C:\project\node_modules\promise-retry\index.js:29:24
    at <anonymous>

**Comment by xavi-** [comment]
Added support for promises in [`0.5.0`](https://www.npmjs.com/package/simple-rate-limiter/v/0.5.0).  Example usage:

```js
const promiser = num => new Promise(resolve => resolve(num * 2));
const limited = limit.promise(promiser).to(5).per(1000);

const numbers = [ 1, 2, 3, 4, 5, 6, 7, 8, 9 ];
const doubled = await Promise.all(numbers.map(num => limited(num)));

assert.deepEqual(doubled, [ 2, 4, 6, 8, 10, 12, 14, 16, 18 ]);
```
